services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migrate

  #    environment:
  #      - DJANGO_SUPERUSER_USERNAME=admin
  #      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
  #      - DJANGO_SUPERUSER_PASSWORD=mypass
  #    depends_on:
  #      - populate
  #  populate:
  #    build: .
  #    command: python populate_db.py
  #    depends_on:
  #      - migrate
  migrate:
    build: .
    command: python manage.py migrate
    depends_on:
      - make-migrations
  make-migrations:
    build: .
    command: python manage.py makemigrations