services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    #    environment:
    #      - "POSTGRES_HOST_AUTH_METHOD=trust"
    environment:
      - POSTGRES_DB=fhir_db
      - POSTGRES_USER=fhir_user
      - POSTGRES_PASSWORD=fhir
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    #    environment:
    #      - POSTGRES_DB=fhir_db
    #      - POSTGRES_USER=fhir_user
    #      - POSTGRES_PASSWORD=fhir
    depends_on:
      - db