# Generated by Django 4.0.4 on 2022-04-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
                ('encounter_class', models.CharField(max_length=50)),
                ('encounter_type', models.CharField(max_length=100)),
                ('primary_performer', models.CharField(max_length=300)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('discharge_disposition', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('service_provider', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=10)),
                ('given_names', models.CharField(max_length=250)),
                ('family_name', models.CharField(max_length=50)),
                ('maiden_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=25)),
                ('address_line', models.CharField(max_length=500)),
                ('address_city', models.CharField(max_length=50)),
                ('address_district', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=50)),
                ('address_postal_code', models.CharField(max_length=20)),
                ('address_country', models.CharField(max_length=50)),
                ('medical_record_number', models.CharField(max_length=50)),
                ('social_security_number', models.CharField(max_length=50)),
                ('drivers_licence', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExplanationOfBenefit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=25)),
                ('use', models.CharField(max_length=25)),
                ('billable_start_datetime', models.DateTimeField()),
                ('billable_end_datetime', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('insurance', models.CharField(max_length=300)),
                ('facility', models.CharField(max_length=300)),
                ('claim_id', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('total_currency', models.CharField(max_length=5)),
                ('payment_amount', models.DecimalField(decimal_places=10, max_digits=10)),
                ('payment_currency', models.CharField(max_length=5)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir_db.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir_db.patient')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir_db.patient'),
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('clinical_status', models.CharField(max_length=20)),
                ('severity', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(max_length=1000)),
                ('body_site', models.CharField(max_length=500)),
                ('onset_datetime', models.DateTimeField()),
                ('record_datetime', models.DateTimeField()),
                ('abatement_datetime', models.DateTimeField()),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir_db.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir_db.patient')),
            ],
        ),
    ]
