# Generated by Django 4.0.4 on 2022-04-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fhir_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='body_site',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='diagnosis',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='severity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='discharge_disposition',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_class',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='primary_performer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='reason',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='service_provider',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='claim_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='facility',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='insurance',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='outcome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='payment_amount',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='payment_currency',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='total_currency',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='use',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_line',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='drivers_licence',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='maiden_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='social_security_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
