# Generated by Django 4.0.4 on 2022-04-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fhir_db', '0002_alter_condition_body_site_alter_condition_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='abatement_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
