# Generated by Django 4.0.4 on 2022-04-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fhir_db', '0003_alter_condition_abatement_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='payment_amount',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
