# Generated by Django 4.0.4 on 2022-04-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fhir_db', '0004_alter_explanationofbenefit_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='payment_amount',
            field=models.DecimalField(decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='explanationofbenefit',
            name='total_amount',
            field=models.DecimalField(decimal_places=50, max_digits=100, null=True),
        ),
    ]
