# Generated by Django 4.0.4 on 2022-04-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fhir_db', '0005_alter_explanationofbenefit_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prefix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
